teamsite/r_shunsuket/urls.py
from django.urls import path

from . import views

app_name = 'r_shunsuket'
urlpatterns = [
    path('/main', views.main, name='main'),
    path('/front', views.front, name='front'),
]

teamsite/r_umetea/urls.py
from django.urls import path

from . import views

app_name = 'r_umetea'
urlpatterns = [
    path('/main', views.main, name='main'),
    path('/response_test', views.response_test, name='response_test'),
    path('/front', views.front, name='front'),
    path('/about', views.about, name='about'),
    path('/error', views.error, name='error'),
]

teamsite/teamsite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'',include('top.urls')),
    path(r'r_umetea',include('r_umetea.urls')),
    path(r'r_shunsuket',include('r_shunsuket.urls')),
]

teamsite/top/urls.py
from django.urls import path,include
from . import views

app_name = 'top'
urlpatterns = [
    path('', views.index, name='index'),
]

teamsite/r_sendo111/models.py
from django.db import models

# Create your models here.

teamsite/r_shunsuket/models.py
from django.db import models

class Post(models.Model):
    message = models.TextField(max_length=4000)
    created_at = models.DateTimeField(auto_now_add=True)
    

teamsite/r_sendo111/views.py
from django.shortcuts import render

# Create your views here.

teamsite/r_shunsuket/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse

def main(req):
    return render(req, 'index.html',{})

def front(req):
    return HttpResponse("ここはフロントページです")

teamsite/r_umetea/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import View
from django.views.generic import TemplateView
import random


def main(req):
    return render(req, 'r_umetea/index.html')


def response_test(req):
    return HttpResponse("レスポンステスト")


class About(View):
    def get(self, req, *args, **kwargs):
        return render(req, 'r_umetea/about.html')


about = About.as_view()


class Omikuji:
    def tenki(self):
        ran = random.choice(list(range(5)))
        if ran == 0:
            result = "たぶん晴れ"
        elif ran == 1:
            result = "曇りかも"
        elif ran == 2:
            result = "わかんない"
        elif ran == 3:
            result = "雨だったら嫌"
        elif ran == 4:
            result = "知らんけどそんなことよりお寿司食べたい"
        return result

    def unsei(self):
        ran = random.choice(list(range(10)))
        list_message = {0: "大吉", 1: "結構ハッピー", 2: "ちょっとはいいことあるかも", 3: "平凡ないつも通りの一日",
                        4: "凶なのでガチャは爆死", 5: "大凶", 6: "絶望", 7: "悪夢", 8: "地獄", 9: "終末"}
        result = list_message[ran]
        return result


class Front(TemplateView):
    template_name = "r_umetea/front.html"
    c = Omikuji()
    tenki = c.tenki
    unsei = c.unsei
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tenki"] = self.tenki
        context["unsei"] = self.unsei
        return context

front = Front.as_view()


def error(req):
    return render(req, 'r_umetea/error.html')

teamsite/top/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse

def index(req):
    return render(req,'top/index.html')

teamsite/r_shunsuket/templates/index.html
{% load static %}

<a href="{% url 'top:index' %}">TOPに戻るよ</a>
hogehoges

teamsite/r_umetea/templates/r_umetea/about.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>umeteaのページだよ</title>
        <meta charset="utf-8">
        <!-- CDN CSS(Karma CSS)
        https://karmacss.com/en/latest/installation.html -->
        <link rel="stylesheet" href="https://unpkg.com/karma-css@latest/dist/karma.min.css">

        <!-- static配下のCSSファイルを参照 -->
        <link rel="stylesheet"
        href="{% static 'css/todo.css' %}" >
    </head>
    <body>
        <div class="container">
            <h1>umeteaのAboutページです</h1>
        </div>
        <br>
        <h2><a href="{% url 'r_umetea:main' %}">umeteaの部屋入口へ</a></h2>
        <br>
        <h2><a href="{% url 'top:index' %}">topへ</a></h2>

    </body>
</html>

teamsite/r_umetea/templates/r_umetea/error.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>エラー</title>
        <meta charset="utf-8">
        <!-- CDN CSS(Karma CSS)
        https://karmacss.com/en/latest/installation.html -->
        <link rel="stylesheet" href="https://unpkg.com/karma-css@latest/dist/karma.min.css">

        <!-- static配下のCSSファイルを参照 -->
        <link rel="stylesheet"
        href="{% static 'css/todo.css' %}" >
    </head>
    <body>
        <div class="container">
            <h1>エラーが発生しました</h1>
        </div>
        <br>
        <h2><a href="{% url 'top:index' %}">topへ</a></h2>

    </body>
</html>

teamsite/r_umetea/templates/r_umetea/front.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>umeteaのページだよ</title>
        <meta charset="utf-8">
        <!-- CDN CSS(Karma CSS)
        https://karmacss.com/en/latest/installation.html -->
        <link rel="stylesheet" href="https://unpkg.com/karma-css@latest/dist/karma.min.css">

        <!-- static配下のCSSファイルを参照 -->
        <link rel="stylesheet"
        href="{% static 'css/todo.css' %}" >
    </head>
    <body>
        <div class="container">
            <h1>umeteaのフロントページです</h1>
        </div>
        <div class="view"><a class="message">今日の天気は[</a>{{ tenki }}<a class="message">]です！</a></div>
        <div class="view"><a class="message">今日のあなたの運勢は[</a>{{ unsei }}<a class="message">]です！</a></div>
        <br>
        <h2><a href="{% url 'r_umetea:main' %}">umeteaの部屋入口へ</a></h2>
        <br>
        <h2><a href="{% url 'top:index' %}">topへ</a></h2>

    </body>
</html>

teamsite/r_umetea/templates/r_umetea/index.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>umeteaのページだよ</title>
    </head>
    <body>
        <div class="container">
            <h2>umeteaの個人ページです</h2>
        </div>
        <h1><a href="{% url 'r_umetea:front' %}">umeteaの部屋。フロント</a></h1>
        <h1><a href="{% url 'top:index' %}">topへ</a></h1>

    </body>
</html>

teamsite/top/templates/top/index.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>トップページだよ</title>
    </head>
    <body>
        <div class="container">
            <h2>ここはチームサイトです</h2>
        </div>
        <h1><a href="{% url 'top:index' %}">topへ</a></h1>
        <h1><a href="{% url 'r_umetea:main' %}">umeteaの部屋。view呼び出し</a></h1>
        <h1><a href="{% url 'r_shunsuket:main' %}">shunsuke-tの部屋。view呼び出し</a></h1>
    </body>
</html>